### PR TITLE
fix: make sure the default position is absolute when using pure inline styles

### LINKED ISSUE #410: onChange event for MentionsInput component captures arrow keys, but not mouse clicks
**Steps to reproduce:**

Using a very simple example of the MentionsInput component, with a simple onChange function instead of the recompose handlers from the examples.

This works fine for keyboard events (trigger with '@', and navigate suggestions list with arrow keys + enter). However clicking on suggestions in the list simply closes the list, rather than selecting the clicked item. And the function supplied to onChange is never called for click events.

Is there a good way to enable click events through a simple onChange function, without importing the 'recompose' handlers from the examples?

```
class App extends Component {
  
  constructor(){
    super()
    this.state = {
      aValue: 'beep beep',
      users: [ {id: 'walter',display: 'Walter White',}, {id: 'jesse', display: 'Jesse Pinkman',}, {id: 'gus', display: 'Gustavo "Gus" Fring',}, ]
    }
  }
  
  handleChange(event){
    console.log('change event did run')
    this.setState({
      aValue: event.target.value,
    });
  }

  render() {
    return (
      <div className="App">
        <MentionsInput
          value={this.state.aValue}
          placeholder={"Mention people using '@'"}
          onChange={this.handleChange.bind(this)}
          style={styleBlock}
        >
          <Mention data={ this.state.users } />

        </MentionsInput>
      </div>
    );
  }
}
```

**Expected behaviour:**
Clicking on a suggestion will select that suggestion, or at least fire onChange event

**Observed behaviour:**
Clicking on a suggestion closes the suggestionlist without firing onChange event

**Workaround:**
None

### PR DESCRIPTION
**Pull request by jfschwarz**
this keeps the overlay clickable and fixes #410

### CODE REVIEW

File: src/SuggestionsOverlay.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ class SuggestionsOverlay extends Component {
 
     return (
       <div
-        {...inline(style, { position, left, top })}
+        {...inline({ position: position || 'absolute', left, top }, style)}
```
Comment (jfschwarz) [inline src/SuggestionsOverlay.js:85]: the switch of order here allows users to potentially override the assigned position, e.g., for rendering the suggestions below the input instead of as an overlay

File: src/SuggestionsOverlay.js [hunk 2]
```diff
@@ -82,7 +82,7 @@ class SuggestionsOverlay extends Component {
 
     return (
       <div
-        {...inline(style, { position, left, top })}
```
Comment (jfschwarz) [inline src/SuggestionsOverlay.js:85]: the problem here is, that the `position: undefined` inline style overrides the default `position: 'absolute'`
